# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculate.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'calculate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61lculate.proto\x12\ncalculator\"#\n\x0bValuesInput\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x19\n\nCalcOutput\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x32H\n\nCalculator\x12:\n\x07\x43\x61lcSum\x12\x17.calculator.ValuesInput\x1a\x16.calculator.CalcOutputb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALUESINPUT']._serialized_start=31
  _globals['_VALUESINPUT']._serialized_end=66
  _globals['_CALCOUTPUT']._serialized_start=68
  _globals['_CALCOUTPUT']._serialized_end=93
  _globals['_CALCULATOR']._serialized_start=95
  _globals['_CALCULATOR']._serialized_end=167
# @@protoc_insertion_point(module_scope)
