# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import get_multiples_of_pb2 as get__multiples__of__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in get_multiples_of_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MultiplesOfStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckAll = channel.stream_stream(
                '/MultiplesOf/CheckAll',
                request_serializer=get__multiples__of__pb2.Number.SerializeToString,
                response_deserializer=get__multiples__of__pb2.Number.FromString,
                _registered_method=True)


class MultiplesOfServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckAll(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MultiplesOfServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckAll': grpc.stream_stream_rpc_method_handler(
                    servicer.CheckAll,
                    request_deserializer=get__multiples__of__pb2.Number.FromString,
                    response_serializer=get__multiples__of__pb2.Number.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MultiplesOf', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MultiplesOf', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MultiplesOf(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckAll(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/MultiplesOf/CheckAll',
            get__multiples__of__pb2.Number.SerializeToString,
            get__multiples__of__pb2.Number.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
